### ISSUE TITLE
Conflicts

### ISSUE THREAD

**Issue by veez21** [sohamxda7/-UNIVERSAL-SUPER-FAST-MOD-Ultimate-Performance-Blazing-Fast-Speed-On-The-Go-#2]
Many conflicting scripts, like ram_manager and ram_optimize, basically the other one is useless and so are the other scripts that conflicts. And the some scripts are not universal and will not play well with others, causing instability. 😇😇

**Comment by storm1er** [comment]
Let's check this, but i'm going to deal with those install / uninstall script which use different functions doing the same things. Could you list all scripts conflictings which one etc ? That would help a lot, Thanks ;)

**Comment by sohamxda7** [comment]
im thinking about rebuilding from scratch

**Comment by storm1er** [comment]
Well, can you link me all script you used to build yours ? So we can
refresh your work faster ;)

**Comment by sohamxda7** [comment]
BroadCom Boostser --> http://forum.xda-developers.com/showthread.php?t=2494092
Pure Performances X ---> http://forum.xda-developers.com/showthread.php?t=2360670
Fly on mod --> http://forum.xda-developers.com/showthread.php?t=2226373
Adrenaline engine --> http://forum.xda-developers.com/showthread.php?t=1579710

**Comment by storm1er** [comment]
BroadCom Booster **OK**
PurePerformance X **OK**
Adrenaline Engine **OK**
Fly On Mod **Hmm**

Sqlite installation is quite a mess with this one, You can [see here](https://github.com/storm1er/oukitelK6000Pro-tetherLimitByPass/blob/master/setup/edit_APNs.sh#L24) that sqlite isn't easy to manage ... so I think we should give up this one, for the moment ^^'

EDIT : and my script doesn't install sqlite :/ Fly On Mod need a real installation with dynamic libraries :(

**Comment by storm1er** [comment]
> sohamsen said : 
sqlite gives a boost  
is is really need to be removed?  

Well, to be fair, your mod doesn't include it. And sqlite is supposed to be installed only on custom roms or on developper's stock rom.
So everyone here, with stock rom, doesn't have sqlite, even with your mod installed. (exception of people who already install it through another mod)

EDIT : Sorry, your mod include default version of sqlite3 in /system/etc/CrossBreeder/sqlite3
But it's only one version ... as I already said, there is multiple version of it, especially if you want your mod to be universal.

**Comment by veez21** [comment]
the binaries used are old, lollipop+ doesn't support non-pie binaries, you need to update them, googling will help

**Comment by storm1er** [comment]
yup, as we can [see here](http://stackoverflow.com/a/30547603). 
My script contains compiled version of sqlite. We will use this for the beginning. 

So now, the forth mod can be included :)

I'll make a first "merge" with everything this w-e.

**Comment by sohamxda7** [comment]
OK BRO :)

**Comment by storm1er** [comment]
Ok guys, news : 

Don't forget that every mod here is kinda outdated : last update are from 2013/2014
So we will have to make some test before telling people 'Yay, v1.0 is out !' ...

Fly-On-Mod is just OUTDATED ... it started in 2013, still updated but used by apps.
Lasts posts of Fly-On-Mod's thread you send clearly said it's outdated : 
'Use app, it's more stable'
It's clearly a bad idea to use it. They just give up "script-update" method.
(+ links are broken on thread ...)

Anyway, here where i'm I : 
Adreline Engine(A.E.) will be base : Nothing will override A.E.'s files
Then Pure Performance X (P.P.X.) to complete : Nothing will override P.P.X.'s files
(PPX contains AE already, that's why not in first)
Then BroadCom Booster.

**Comment by storm1er** [comment]
Does anyone know where to find a zipalign PIE binary ? ôO ?

**Comment by storm1er** [comment]
https://github.com/sohamxda7/-UNIVERSAL-SUPER-FAST-MOD-Ultimate-Performance-Blazing-Fast-Speed-On-The-Go-/pull/4

Ok, clean working directory, @sohamxda7 Can you build a clean uninstaller of you previous build ?
(and eventually for this new version if you feel motivated ^^)

**Comment by sohamxda7** [comment]
ok i will let me download the repo

**Comment by storm1er** [comment]
@sohamxda7 If you need help about github, ask here ;) 

EDIT : Arf, just realised we forgot TweakZV6 :|

**Comment by sohamxda7** [comment]
ya

**Comment by sohamxda7** [comment]
Download Links
TweakZv6 https://www.datafilehost.com/d/2e5bdd5f

LagFree v3 https://www.datafilehost.com/d/36f527d5

Cosmic Tweaks https://www.datafilehost.com/d/1ca3293

Check these out 

should we add them ?

**Comment by storm1er** [comment]
Hmm, let's make an issue of them  [ISSUE LINK](https://github.com/sohamxda7/-UNIVERSAL-SUPER-FAST-MOD-Ultimate-Performance-Blazing-Fast-Speed-On-The-Go-/issues/5) ,
We'll see later for new merge, before we have to fix some stuff on our base code. (like zipalign for example :/) [ISSUE LINK](https://github.com/sohamxda7/-UNIVERSAL-SUPER-FAST-MOD-Ultimate-Performance-Blazing-Fast-Speed-On-The-Go-/issues/6)

You said your uninstaller is ready, can you push it ? Thanks 

This issue is closed since  https://github.com/sohamxda7/-UNIVERSAL-SUPER-FAST-MOD-Ultimate-Performance-Blazing-Fast-Speed-On-The-Go-/pull/4/commits/899465c0f031352759b25a47ea913834df40e8f5

There's no more conflicts.

**Comment by storm1er** [comment]
This issue is closed since  https://github.com/sohamxda7/-UNIVERSAL-SUPER-FAST-MOD-Ultimate-Performance-Blazing-Fast-Speed-On-The-Go-/pull/4/commits/899465c0f031352759b25a47ea913834df40e8f5

**Comment by storm1er** [comment]
@sohamxda7 can close this please =)
Resolved by #4

**Comment by storm1er** [comment]
#4
