### ISSUE TITLE
Uninstaller

### ISSUE THREAD

**Issue by sohamxda7** [sohamxda7/-UNIVERSAL-SUPER-FAST-MOD-Ultimate-Performance-Blazing-Fast-Speed-On-The-Go-#7]
https://www.datafilehost.com/d/4d2f43f3

New uninstaller download link.!

please you push i will merge 
as i am pretty noob in github

**Comment by storm1er** [comment]
haha, ok

Well here what i do : 
_consider '/' being the project's root's folder_
- Put your zip in /
- Extract your zip in /uninstaller
- `git status` to check files that i need to add
- `git add [files]`
- `git commit -m "[reason of push]"`
- then finally `git push`

On my side, I need to make a pull request too because i'm not the repo's author.

Your uninstaller is incomplete again ... You have to understand that people doesn't use only our mods : 
When your doing `delete_recursive("/system/etc/init.d");` you delete every start init.d script.
But what if it's a custom rom with some init.d optimisation ? soft brick maybe...

Anyway, i'm pushing this one, but without the zip in /, as we need to complete it.

You'll learn a lot ;)

**Comment by storm1er** [comment]
By the way
`mount("ext4", "EMMC", "/dev/block/mmcblk0p7", "/system");`   
`mount("ext4", "EMMC", "/dev/block/mmcblk0p9", "/data");`

This is ok only for some phones, you can use [this file](https://github.com/sohamxda7/-UNIVERSAL-SUPER-FAST-MOD-Ultimate-Performance-Blazing-Fast-Speed-On-The-Go-/blob/master/installer/setup/auto_mount.sh) in your script with busybox. So we auto-mount /system and /data for people ;)

**Comment by sohamxda7** [comment]
https://www.datafilehost.com/d/5ea36907

New updater script :) check it out 

Im not at home right now im at hostel so i cant access to my pc

please push it

**Comment by storm1er** [comment]
Please, take a look at your uninstaller, then compare it to what I pushed.
- Added cross-platform mount
- More verbose

You should keep in mind that people aren't always nerd ;)
Better output = Better user response

**Comment by storm1er** [comment]
@sohamxda7 Ok
let's update README, and XDA thread

installer : [link](https://github.com/sohamxda7/-UNIVERSAL-SUPER-FAST-MOD-Ultimate-Performance-Blazing-Fast-Speed-On-The-Go-/raw/master/zippedInstaller/ultimate-performance-blazing-speed-v0.4.zip)
uninstaller : [link](https://github.com/sohamxda7/-UNIVERSAL-SUPER-FAST-MOD-Ultimate-Performance-Blazing-Fast-Speed-On-The-Go-/raw/master/zippedUnInstaller/uninstaller-ultimate-performance-blazing-speed-v0.3%2B.zip)

**Comment by sohamxda7** [comment]
ok i will tommorow

**Comment by storm1er** [comment]
Arf, uninstaller doesn't backup build.prop
backup exist `/system/build.prop.backupUPB01`
I'm on it

**Comment by storm1er** [comment]
Fixed
